DATASET:
  TYPE: PRW
  PATH: !include configs/_path_prw.yaml
  BATCH_SIZE: 8
SOLVER:
  MAX_EPOCHS: 20
  OPTIMIZER: 'Adam'
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.0
  BIAS_LR_FACTOR: 1.0
  BIAS_DECAY: 0.0
  SGD_MOMENTUM: 0.0
  LR_DECAY_MILESTONES: [8, 14]
  LR_DECAY_GAMMA: 0.1
MODEL:
  BACKBONE: 'ConvNeXt'
  REID:
    LOSS:
      LUT_SIZE: 483
      CQ_SIZE: 500
      MARGIN: 0.35
  PARAM_INIT: 'v2'
